In [ ]:
#Basic arithmetic
import numpy as np
a = np.array([1, 2, 3, 4])

print(a + 10)   # [11 12 13 14]
print(a - 2)    # [-1  0  1  2]
print(a * 3)    # [ 3  6  9 12]
print(a / 2)    # [0.5 1.  1.5 2. ]
print(a ** 2)   # [ 1  4  9 16]


[11 12 13 14]
[-1  0  1  2]
[ 3  6  9 12]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [5]:
# exp and logs

print(np.exp([0,1,2,3]))

print(np.log([1,np.e,np.e**2]))

print(np.log10([1,10,100]))

[ 1.          2.71828183  7.3890561  20.08553692]
[0. 1. 2.]
[0. 1. 2.]


In [10]:
x = np.array([0, np.pi/2, np.pi])
print(np.sin(x))  # [0. 1. 0.]
print(np.cos(x))  # [1. 0. -1.]
print(np.tan(x))  # [0. inf 0.]  (tan(pi/2) is undefined → inf)

a = np.sin(x)
b = np.cos(x)
c = np.tan(x)

print("-------------------------")

print(np.floor(a))
print(np.floor(b))
print(np.floor(c))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
-------------------------
[0. 1. 0.]
[ 1.  0. -1.]
[ 0.00000000e+00  1.63312394e+16 -1.00000000e+00]
